name: Test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: gosec
      run: |
        go get github.com/securego/gosec/cmd/gosec
        $(go env GOPATH)/bin/gosec .
    - name: golint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
        $(go env GOPATH)/bin/golangci-lint run ./...
    - name: Test
      run: go test -v ./...
